// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzprnxwezcsvqrsklwhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6cHJueHdlemNzdnFyc2tsd2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDMyMjAsImV4cCI6MjA2NTMxOTIyMH0.BZLg3kBg3D_QVVn06pKH-J0TeR4YGq2mC6i2puENeOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);